[theme]
# Primary accent for interactive elements
primaryColor = "#b27eff"

# Background color for the main content area
backgroundColor = "#EFE9F4"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#A592B1"

# Color used for almost all text
textColor = '#000000'
