[theme]
base = "light"

# Primary accent for interactive elements
primaryColor = "#002D80"

# Background color for the main content area
backgroundColor = "#C4C3C2"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#9DA4B3"

# Color used for almost all text
#textColor = '#000000'
